### ISSUE TITLE
Provide a systemd unit

### ISSUE THREAD

**Issue by tanshoku** [sp1ff/mpdpopm#4]
Here's what I'm currently using:

```
[Unit]
Description=mpdpopm ratings and playcounts for MPD
Requires=mpd.service
After=mpd.service

[Service]
Restart=on-failure
ExecStart=/usr/local/bin/mppopmd -F -c %h/.config/mppopmd.conf

[Install]
WantedBy=default.target
```

this works fine and logs to the system journal, as expected, which also provides log rotation. I've only been using mpdpopm for a day, but it showed itself to be a lot better than mpdfav, which used to crash all the time, and is generally more configurable as well.

**Comment by sp1ff** [comment]
Thanks @tanshoku ! Thinking about how to distribute this... I'm not sure systemd unit files are installed in the same place across Linux distros, let alone leaving the option of how to install it as a "user" unit.
In defence of mpdfav, Rust lets you catch a lot of errors at compile-time that will only manifest at run-time with Golang-- a big part of why I chose it. I learned a lot reading the mpdfav source!

**Comment by tanshoku** [comment]
According to [this answer on stackexchange](https://unix.stackexchange.com/a/367237), systemd units can *technically* go anywhere, although the usual places are `/etc/systemd/system`, `/etc/systemd/user`, `/usr/local/lib/systemd/system`, `/usr/local/lib/systemd/user`,  or `$HOME/.config/systemd/user`, the last being where I put mine. Ideally, though, it should probably go under one of the `/usr` or `/etc` locations, so the unit is available globally on multi-user systems.

**Comment by sp1ff** [comment]
Decided to add it under `/usr/local/lib/systemd`, since 1) the binaries go under `/usr/local` by default & 2) that's where MPD puts its units. Added in 0.1.15. Thanks!
