### ISSUE TITLE
Archlinux packages - precompiled and source

### ISSUE THREAD

**Issue by m040601** [sp1ff/mpdpopm#6]
Hi sp1ff,

thanks again for your work in this tool. And thanks for providing a Archlinux precompiled package. 
> 
> ...I’ve begun providing a Arch binary package. Just do:
> curl -L -O https://github.com/sp1ff/mpdpopm/releases/download/0.3.0/mpdpopm_0.3.0-1-x86_64.pkg.tar.zst
> sudo pacman -U mpdpopm_0.3.0-1-x86_64.pkg.tar.zst
> 

Since I'm not sure if you are an Archlinux user or not (can you confirm please ?), and might require any assistance, just a quick question and remark.

1. Use the AUR not github

I'm wondering if you're planning to add this it to the "right" place, that is the AUR repository, https://aur.archlinux.org/

I'm asking this, because I see now that you also make an effort to provide a Debian package. So  I suspect now you're a Debian user. But ideally, it should be enough for you to worry about the source and the precompiled binary. The packaging should be the burden of the package managers of the distro.

1.1. For the **precompiled binary package** , this should be something like mpdpopm-bin

The "bin package" itself, is a just an easy peasy recipe, a PKGBUILD. That comes to github grabs the bin with curl and puts it on the right place.

You dont need to keep a mpdpopm.zstd arch package in github. Just the x86 binary. The package is built (basicly just downloading) by each arch user, from a PKGBUILD in the AUR using his tool of choice.

Additionaly a template for a systemd unit for the user.
Additionally, the README and the man page can be pullled from github as well, to end up in /usr/share/doc/mpdpopm/README etc.

It would be nice if the developer himself, did this, as it could also additionally be signed.

1.2. Are you planning to create a **source package PKGBUILD** in the AUR as well ?

2.  Binaries in /usr/local/bin in Archlinux

> The binaries will be placed in /usr/local/bin,

This is not correct, and needs to be changed anyway, to /usr/bin

https://wiki.archlinux.org/title/Arch_package_guidelines
> Packages should never be installed to /usr/local/

3. Systemd unit

> ... decided to add it under /usr/local/lib/systemd, since 1) the binaries go under /usr/local by default & 2) that's where MPD puts its units. ...

> ... I'm not sure systemd unit files are installed in the same place across Linux distros, let alone leaving the option of how to install it as a "user" unit.

This is again the same issue. Archlinux does not use /usr/local.
So the standard way would indeed be this:

> or $HOME/.config/systemd/user, the last being where I put mine. Ideally, though, it should probably go under one of the /usr or /etc locations, so the unit is available globally on multi-user systems.

**Comment by sp1ff** [comment]
Hey @m040601, sorry for the tardy response (day job has been keeping me busy).
To answer your first question, I use both Debian (at work) and Arch (at home). No Fedora in my life, right now. Oh-- and for context, I provide the Debian binary package via a Cargo extension ([cargo-deb](https://github.com/mmstick/cargo-deb)) whereas I build the Arch binary package via `makepkg` in an Arch Linux container. I setup both in response to your Issue #2 (Provide Binary Releases) out of a general effort to make installing easier, but before I had much experience with packaging (on any platform).
Let me try to break-out your issues individually & make sure I understand them:

  1. The Arch package should be hosted at the AUR, not github. 

That's a fair point. TBH it just didn't occur to me (I may not even have been aware of the AUR when I set this up). While I'm certainly not _opposed_ to it, I sense that you would prefer that a binary package *not* be hosted here at all. Can I ask why?

  2. There should be a binary _and_ a source package on AUR

Now here I'm confused-- I had thought the AUR was exclusively source packages. IOW, whenever I've installed something from the AUR, I've had to `git clone` the package repo, which would include a `PKGBUILD` & maybe some patches, then do a `makepkg` & `packman -U`. Which seemed inconvenient to me, in comparison to just providing users with a `.pkg.tar.zstd` as I do today.

Also, pulling a dynamically-linked binary down from github seems brittle-- it's likely that the user's machine will either lack .so-s on which my binary depends or have the wrong versions installed. But perhaps I'm confused-- let me look into it further.

  3. The source package uses `/usr/local`

Fair. Will review the Arch packaging guidelines & update.

Thanks for the suggestionst!

**Comment by m040601** [comment]
> ... I sense that you would prefer that a binary package not be hosted here at all. Can I ask why?


Let me clarify. We're talking about two different things here.

- the precompiled linux x64 binary (should/could be universal and work  for many different Linux distros)
- the "zstd" arch package - something specific to arch linux

The precompiled binary can be hosted on github. But the final "zstd" package is cooked/assembled in the user's computer, by using a recipe (PKGBUILD) available on the AUR. You dont host the "zstd" on the AUR. You just host the recipe.


The AUR is just a shop, a catalog of recipes. It doest host any binary files. Those are pulled from their original developer repos.

Other wise an Arch User would have to individually go to your and others github repo for every single binary package. Not practical


> I had thought the AUR was exclusively source packages.

No, not at all. There are both package that you pull the "source" and compile in your computer as well as "bin" packages that simply pull a precompiled binary from somewhere.

> ...whenever I've installed something from the AUR, I've had to git clone ... then do a makepkg & packman -U. ..Which seemed inconvenient to me,

I sense that you're not yet very familiar with the AUR and it's helper tools.
I recommend that you try one. I recommend "yay" the most popular.

https://wiki.archlinux.org/title/AUR_helpers

Have a look here,
https://aur.archlinux.org/packages/?O=0&K=-bin&SB=p&SO=d

You'll see that there are many popular softwares available in the AUR has "xxxx-bin". For example the brave browse, and pandoc.

They are also available as source package. They are even available in the official arch repo. But these AUR "-bin"'s provide an alternative for simply pulling precompiled binaries, instead of pulling huge dependecies and long compilation times on your computer


This way an arch linux user has "one place" shop to search for stuff.
Search is the keyword here.
It's a place also to "find" stuff for Arch.

**Comment by sp1ff** [comment]
> There are 3 types of PKGBUILDS, recipes , on the AUR.

Ah, yes, I see.

> Maybe you are confusing the AUR with having a personal arch repository, and hosting your own pre assembled "zstd's" there ?

No not really. My thinking was more that `mpdpopm` is a small, obscure project and as such not suitable for hosting in a package repository of any sort, not even the AUR. Hence someone interested in `mpdpopm` would likely already be at Github & looking for the easiest way to install it. Hosting a "zstd" was, in my mind, a service to Arch users.

> I recommend that you try one. I recommend "yay" the most popular.

Will look, but I prefer to learn "by hand" first and only use a "helper" only once I understand how it's "helping" me :)

OK, let me re-formulate this issue. How about: 

## Please host Arch packages in the canonical location, which is the AUR, not Github

Furthermore, both `mpdpopm-bin` (i.e. grab the pre-built binaries) & `mpdpopm` (grab a given Autotools tarball) variants would be nice.

Does that capture it?

**Comment by m040601** [comment]
Yes I think, now it all seems much clear.

` ... My thinking was more that mpdpopm is a small, obscure project and as such not suitable for hosting in a package repository of any sort, not even the AUR. ...`

No !!! Dont' think like that. That is precisely the greatest strength of the AUR and Archlinux. To provide a central place for discovery for all those projects that might not be so "famous".

This (with other things) is what makes Archlinux great.

**Comment by sp1ff** [comment]
Alright, well, it took a while, but I eventually addressed this. Arch package removed from the releases here & now hosted at the [AUR](https://aur.archlinux.org/packages?O=0&SeB=n&K=mpdpopm&outdated=&SB=p&SO=d&PP=50&submit=Go).
